export const allCountry = [
  {
    code: 'ad',
    name: 'Андорра',
    price: '12 022',
    img: '/assets/img/svg/flags/ad.svg',
  },
  {
    code: 'ae',
    name: 'ОАЭ',
    price: '12 022',
    img: '/assets/img/svg/flags/ae.svg',
  },
  {
    code: 'al',
    name: 'Албания',
    price: '12 022',
    img: '/assets/img/svg/flags/al.svg',
  },
  {
    code: 'az',
    name: 'Азербайджан',
    price: '12 022',
    img: '/assets/img/svg/flags/az.svg',
  },
  {
    code: 'bg',
    name: 'Болгария',
    price: '12 022',
    img: '/assets/img/svg/flags/bg.svg',
  },
  {
    code: 'ch',
    name: 'Швейцария',
    price: '12 022',
    img: '/assets/img/svg/flags/ch.svg',
  },
  {
    code: 'cn',
    name: 'Китай',
    price: '12 022',
    img: '/assets/img/svg/flags/cn.svg',
  },
  {
    code: 'cu',
    name: 'Куба',
    price: '12 022',
    img: '/assets/img/svg/flags/cu.svg',
  },
  {
    code: 'cy',
    name: 'Кипр',
    price: '12 022',
    img: '/assets/img/svg/flags/cy.svg',
  },
  {
    code: 'cz',
    name: 'Чехия',
    price: '12 022',
    img: '/assets/img/svg/flags/cz.svg',
  },
  {
    code: 'do',
    name: 'Доминикана',
    price: '12 022',
    img: '/assets/img/svg/flags/do.svg',
  },
  {
    code: 'eg',
    name: 'Египет',
    price: '12 022',
    img: '/assets/img/svg/flags/eg.svg',
  },
  {
    code: 'es',
    name: 'Испания',
    price: '12 022',
    img: '/assets/img/svg/flags/es.svg',
  },
  {
    code: 'fr',
    name: 'Франция',
    price: '12 022',
    img: '/assets/img/svg/flags/fr.svg',
  },
  {
    code: 'ge',
    name: 'Грузия',
    price: '12 022',
    img: '/assets/img/svg/flags/ge.svg',
  },
  {
    code: 'gr',
    name: 'Греция',
    price: '12 022',
    img: '/assets/img/svg/flags/gr.svg',
  },
  {
    code: 'hr',
    name: 'Хорватия',
    price: '12 022',
    img: '/assets/img/svg/flags/hr.svg',
  },
  {
    code: 'hu',
    name: 'Венгрия',
    price: '12 022',
    img: '/assets/img/svg/flags/hu.svg',
  },
  {
    code: 'id',
    name: 'Индонезия',
    price: '12 022',
    img: '/assets/img/svg/flags/id.svg',
  },
  {
    code: 'il',
    name: 'Израиль',
    price: '12 022',
    img: '/assets/img/svg/flags/il.svg',
  },
  {
    code: 'in',
    name: 'Индия',
    price: '12 022',
    img: '/assets/img/svg/flags/in.svg',
  },
  {
    code: 'it',
    name: 'Италия',
    price: '12 022',
    img: '/assets/img/svg/flags/it.svg',
  },
  {
    code: 'jo',
    name: 'Иордания',
    price: '12 022',
    img: '/assets/img/svg/flags/jo.svg',
  },
  {
    code: 'lk',
    name: 'Шри-Ланка',
    price: '12 022',
    img: '/assets/img/svg/flags/lk.svg',
  },
  {
    code: 'ma',
    name: 'Марокко',
    price: '12 022',
    img: '/assets/img/svg/flags/ma.svg',
  },
  {
    code: 'me',
    name: 'Черногория',
    price: '12 022',
    img: '/assets/img/svg/flags/me.svg',
  },
  {
    code: 'mt',
    name: 'Мальта',
    price: '12 022',
    img: '/assets/img/svg/flags/mt.svg',
  },
  {
    code: 'mu',
    name: 'Маврикий',
    price: '12 022',
    img: '/assets/img/svg/flags/mu.svg',
  },
  {
    code: 'mv',
    name: 'Мальдивы',
    price: '12 022',
    img: '/assets/img/svg/flags/mv.svg',
  },
  {
    code: 'mx',
    name: 'Мексика',
    price: '12 022',
    img: '/assets/img/svg/flags/mx.svg',
  },
  {
    code: 'pt',
    name: 'Португалия',
    price: '12 022',
    img: '/assets/img/svg/flags/pt.svg',
  },
  {
    code: 'qa',
    name: 'Катар',
    price: '12 022',
    img: '/assets/img/svg/flags/qa.svg',
  },
  {
    code: 'sc',
    name: 'Сейшельские о-ва',
    price: '12 022',
    img: '/assets/img/svg/flags/sc.svg',
  },
  {
    code: 'sg',
    name: 'Сингапур',
    price: '12 022',
    img: '/assets/img/svg/flags/sg.svg',
  },
  {
    code: 'th',
    name: 'Таиланд',
    price: '12 022',
    img: '/assets/img/svg/flags/th.svg',
  },
  {
    code: 'tn',
    name: 'Тунис',
    price: '12 022',
    img: '/assets/img/svg/flags/tn.svg',
  },
  {
    code: 'tr',
    name: 'Турция',
    price: '12 022',
    img: '/assets/img/svg/flags/tr.svg',
  },
  {
    code: 'tz',
    name: 'Танзания',
    price: '12 022',
    img: '/assets/img/svg/flags/tz.svg',
  },
  {
    code: 'vn',
    name: 'Вьетнам',
    price: '12 022',
    img: '/assets/img/svg/flags/vn.svg',
  },
];
