export const allCountry = [
  {
    code: 'AD',
    name: 'Андорра',
    price: '12 022',
    img: '/assets/img/svg/flags/AD.svg',
  },
  {
    code: 'AE',
    name: 'ОАЭ',
    price: '12 022',
    img: '/assets/img/svg/flags/AE.svg',
  },
  {
    code: 'AL',
    name: 'Албания',
    price: '12 022',
    img: '/assets/img/svg/flags/AL.svg',
  },
  {
    code: 'AZ',
    name: 'Азербайджан',
    price: '12 022',
    img: '/assets/img/svg/flags/AZ.svg',
  },
  {
    code: 'BG',
    name: 'Болгария',
    price: '12 022',
    img: '/assets/img/svg/flags/BG.svg',
  },
  {
    code: 'CH',
    name: 'Швейцария',
    price: '12 022',
    img: '/assets/img/svg/flags/CH.svg',
  },
  {
    code: 'CN',
    name: 'Китай',
    price: '12 022',
    img: '/assets/img/svg/flags/CN.svg',
  },
  {
    code: 'CU',
    name: 'Куба',
    price: '12 022',
    img: '/assets/img/svg/flags/CU.svg',
  },
  {
    code: 'CY',
    name: 'Кипр',
    price: '12 022',
    img: '/assets/img/svg/flags/CY.svg',
  },
  {
    code: 'CZ',
    name: 'Чехия',
    price: '12 022',
    img: '/assets/img/svg/flags/CZ.svg',
  },
  {
    code: 'DO',
    name: 'Доминикана',
    price: '12 022',
    img: '/assets/img/svg/flags/DO.svg',
  },
  {
    code: 'EG',
    name: 'Египет',
    price: '12 022',
    img: '/assets/img/svg/flags/EG.svg',
  },
  {
    code: 'ES',
    name: 'Испания',
    price: '12 022',
    img: '/assets/img/svg/flags/ES.svg',
  },
  {
    code: 'FR',
    name: 'Франция',
    price: '12 022',
    img: '/assets/img/svg/flags/FR.svg',
  },
  {
    code: 'GE',
    name: 'Грузия',
    price: '12 022',
    img: '/assets/img/svg/flags/GE.svg',
  },
  {
    code: 'GR',
    name: 'Греция',
    price: '12 022',
    img: '/assets/img/svg/flags/GR.svg',
  },
  {
    code: 'HR',
    name: 'Хорватия',
    price: '12 022',
    img: '/assets/img/svg/flags/HR.svg',
  },
  {
    code: 'HU',
    name: 'Венгрия',
    price: '12 022',
    img: '/assets/img/svg/flags/HU.svg',
  },
  {
    code: 'ID',
    name: 'Индонезия',
    price: '12 022',
    img: '/assets/img/svg/flags/ID.svg',
  },
  {
    code: 'IL',
    name: 'Израиль',
    price: '12 022',
    img: '/assets/img/svg/flags/IL.svg',
  },
  {
    code: 'IN',
    name: 'Индия',
    price: '12 022',
    img: '/assets/img/svg/flags/IN.svg',
  },
  {
    code: 'IT',
    name: 'Италия',
    price: '12 022',
    img: '/assets/img/svg/flags/IT.svg',
  },
  {
    code: 'JO',
    name: 'Иордания',
    price: '12 022',
    img: '/assets/img/svg/flags/JO.svg',
  },
  {
    code: 'LK',
    name: 'Шри-Ланка',
    price: '12 022',
    img: '/assets/img/svg/flags/LK.svg',
  },
  {
    code: 'MA',
    name: 'Марокко',
    price: '12 022',
    img: '/assets/img/svg/flags/MA.svg',
  },
  {
    code: 'ME',
    name: 'Черногория',
    price: '12 022',
    img: '/assets/img/svg/flags/ME.svg',
  },
  {
    code: 'MT',
    name: 'Мальта',
    price: '12 022',
    img: '/assets/img/svg/flags/MT.svg',
  },
  {
    code: 'MU',
    name: 'Маврикий',
    price: '12 022',
    img: '/assets/img/svg/flags/MU.svg',
  },
  {
    code: 'MV',
    name: 'Мальдивы',
    price: '12 022',
    img: '/assets/img/svg/flags/MV.svg',
  },
  {
    code: 'MX',
    name: 'Мексика',
    price: '12 022',
    img: '/assets/img/svg/flags/MX.svg',
  },
  {
    code: 'PT',
    name: 'Португалия',
    price: '12 022',
    img: '/assets/img/svg/flags/PT.svg',
  },
  {
    code: 'QA',
    name: 'Катар',
    price: '12 022',
    img: '/assets/img/svg/flags/QA.svg',
  },
  {
    code: 'SC',
    name: 'Сейшельские о-ва',
    price: '12 022',
    img: '/assets/img/svg/flags/SC.svg',
  },
  {
    code: 'SG',
    name: 'Сингапур',
    price: '12 022',
    img: '/assets/img/svg/flags/SG.svg',
  },
  {
    code: 'TH',
    name: 'Таиланд',
    price: '12 022',
    img: '/assets/img/svg/flags/TH.svg',
  },
  {
    code: 'TN',
    name: 'Тунис',
    price: '12 022',
    img: '/assets/img/svg/flags/TN.svg',
  },
  {
    code: 'TR',
    name: 'Турция',
    price: '12 022',
    img: '/assets/img/svg/flags/TR.svg',
  },
  {
    code: 'TZ',
    name: 'Танзания',
    price: '12 022',
    img: '/assets/img/svg/flags/TZ.svg',
  },
  {
    code: 'VN',
    name: 'Вьетнам',
    price: '12 022',
    img: '/assets/img/svg/flags/VN.svg',
  },
];
