export const links = {
  faq: '/pytannia-vidpovid',
  main: '/',
  tours: '/tury',
  countries: '/countries',
  hotTours: '/hot-tours',
  hotels: '/hotels',
  blog: '/blog',
  blog_category: '/blog/category',
  blog_country: '/blog/country',
  reviews: '/vidhuky',
  certificates: '/podarochnye-sertifikaty',
  contacts: '/contacts',
  telegram: '/',
  viber: 'viber://chat?number=0635914144',
};
