import { useRouter } from 'next/router';
import { IntlProvider } from 'react-intl';
import Head from 'next/head';
import Layout from '../components/common/layout';
import '../styles/globals.css';
import uk from '../lang/uk.json';
import ru from '../lang/ru.json';
import { languagesApi } from 'utils/constants';

const messages = {
  uk,
  ru,
};

function App({ Component, pageProps, navData }) {
  const { locale } = useRouter();

  return (
    <IntlProvider locale={locale} messages={messages[locale]}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"
        />
      </Head>
      <Layout navData={navData}>
        <Component {...pageProps} />
      </Layout>
    </IntlProvider>
  );
}

export default App;

App.getInitialProps = async ({ Component, ctx }) => {
  const loc = languagesApi[ctx.locale];
  const navRes = await fetch(
    `https://a-k.name/directus/items/api_countries?fields=slug,code,translations.languages_code,translations.name&deep[translations][_filter][languages_code][_eq]=${loc}`
  );
  const navData = await navRes.json();
  let pageProps = {};
  if (Component.getInitialProps) {
    pageProps = await Component.getInitialProps(ctx);
  }
  return { pageProps, navData };
};
